connector.name=hive
hive.metastore=glue
hive.metastore.glue.region=ap-northeast-2
hive.metastore.glue.default-warehouse-dir=s3://real-estate-raw/
hive.parquet.use-column-names=true
fs.native-s3.enabled=true 