connector.name=iceberg
iceberg.catalog.type=glue
hive.metastore.glue.region=ap-northeast-2
iceberg.register-table-procedure.enabled=true
# S3 버킷 real-estate-silver에 대한 추가 설정이 필요한 경우
# iceberg.s3.path-style-access=true
# iceberg.s3.endpoint=https://s3.ap-northeast-2.amazonaws.com
# iceberg.s3.aws-access-key=${AWS_ACCESS_KEY_ID}
# iceberg.s3.aws-secret-key=${AWS_SECRET_ACCESS_KEY}

# Trino가 Parquet 파일을 읽을 때 사용할 수 있는 설정 (Iceberg는 기본적으로 컬럼명 사용)
# hive.parquet.use-column-names=true 