apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-frontend-deployment
  namespace: mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvc-frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mvc-frontend
    spec:
      containers:
      - name: mvc-frontend
        image: kdu9303/mvc-frontend:0.1.0
        imagePullPolicy: Always
        env:
        - name: NEXT_PUBLIC_BASE_API
          value: "http://mvc-backend-service.mvc.svc.cluster.local:8000"       
        # envFrom:
        #   - secretRef:
        #     name: mysql-secret        
        resources:
          requests:
            memory: 300Mi
          limits:
            memory: 1Gi
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: mvc-frontend-service
  namespace: mvc
spec:
  selector:
    app: mvc-frontend
  ports:
  - port: 3000
    protocol: TCP 
    targetPort: 3000
  type: LoadBalancer