apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster-webserver
  namespace: argocd
spec:
  destination:
    namespace: dagster
    name: dagster-webserver
  project: default
  sources:
    # Chart from Chart Repo
    - chart: dagster
      repoURL: https://dagster-io.github.io/helm
      targetRevision: 1.5.6
      helm:
        # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
        valueFiles:
        # - $values/path/to/value.yaml
        - $values/k8s/argo-cd/applicattions/dagster/dagster-main-values.yaml
    # Values from Git
    - repoURL: 'https://github.com/greta-inc/infrastructure.git'
      targetRevision: develop
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true