apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster-code-container
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dagster
  sources:
    # Chart from Chart Repo
    - chart: dagster-user-deployments
      repoURL: https://dagster-io.github.io/helm
      targetRevision: 1.5.6
      helm:
        # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
        valueFiles:
        # - $values/path/to/value.yaml
        - $values/k8s/argocd/applicattions/dagster/code-container-values.yaml
    # Values from Git
    - repoURL: git@github.com:greta-inc/infrastructure.git
      targetRevision: develop
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true